name: Security Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  sast-scan:
    uses: ./.github/workflows/sast.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml

  codeQL-scan-analysis:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      security-events: write

  dependency-check:
    uses: ./.github/workflows/dependency-check.yml
