name: DefectDojo Import

on:
  workflow_run:
    workflows:
      - Dependency Check
      - Container Security
    types:
      - completed

jobs:
  import-findings:
    runs-on: ubuntu-latest

    steps:
      - name: Download Dependency-Check artifact
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          workflow: dependency-check.yml
          name: dependency-check-report
          path: dependency-check-report

      - name: Download Trivy artifact
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          workflow: image-scan.yml
          name: trivy-results
          path: trivy-results

      - name: Debug downloaded files
        run: |
          pwd
          find . -type f

      - name: Import Dependency-Check into DefectDojo
        if: hashFiles('dependency-check-report/dependency-check-report.json') != ''
        run: |
          curl -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            -F "scan_type=Dependency Check Scan" \
            -F "file=@dependency-check-report/dependency-check-report.json" \
            -F "active=true" \
            -F "verified=true"

      - name: Import Trivy into DefectDojo
        if: hashFiles('trivy-results/trivy-results.json') != ''
        run: |
          curl -X POST \
            "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            -F "scan_type=Trivy Scan" \
            -F "file=@trivy-results/trivy-results.json" \
            -F "active=true" \
            -F "verified=true"
