name: Image Scan Pipeline(Trivy)

on:
  workflow_call:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t vulnerable-dotnet-app:latest ./app

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vulnerable-dotnet-app:latest
          format: sarif
          exit-code: '0'
          output: trivy-results.sarif
         # severity: HIGH,CRITICAL

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
