name: SAST Pipeline (Semgrep)

on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/src" \
          semgrep/semgrep \
          semgrep scan \
          --config auto \
          --json \
          --output semgrep-results.json \
          /src/app

      - name: Upload Semgrep Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json

      - name: Download Semgrep artifact
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          workflow: ci.yml
          name: semgrep-results
          path: semgrep-results
