name: SAST Pipeline (Semgrep)

on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
