name: SAST Pipeline (Semgrep)

on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          format: sarif
          output: semgrep-results.sarif

      - name: Upload SARIF
        uses: github/semgrep/upload-sarif@v1
        with:
          sarif_file: semgrep-results.sarif
