name: SBOM Pipeline

on:
  workflow_call:

jobs:

  sbom:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: vulnerable-dotnet-app:latest
          formats: spdx-json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: "*.spdx.json"
